import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

const services = [
  ["conference-microphone-interpretation-equipment", "Conference Microphone & Interpretation Equipment", "Audio & Interpretation", "Professional conference audio, microphone systems and simultaneous interpretation booths for multilingual institutional events, government meetings and international conferences.", "/mms/DSC_7204.jpg", ["/mms/DSC_7176.jpg", "/mms/DSC_7204.jpg", "/mms/DSC_7218.jpg"], ["Microphone Systems", "Interpretation Booths", "Receivers & Headsets", "Conference Audio", "Multi-language Support"]],
  ["led-screen-rental", "LED Screen Rental", "Visual Display", "High-brightness LED screens, video walls and digital displays for conferences, brand activations and outdoor events, with on-site technical support.", "/mms/DSC_7215.jpg", ["/mms/DSC_7215.jpg", "/mms/DSC_7176.jpg", "/mms/DSC_7208.jpg"], ["LED Screens", "Indoor & Outdoor", "Video Walls", "Custom Content", "On-site Support"]],
  ["professional-sound-systems", "Professional Sound Systems", "Audio Engineering", "Comprehensive PA systems, line arrays, mixing consoles and wireless microphones engineered for clear, reliable sound at every venue size.", "/mms/Victoria-Falls-Video-Conference-Hire.webp", ["/mms/Victoria-Falls-Video-Conference-Hire.webp", "/mms/DSC_7204.jpg"], ["PA Systems", "Line Arrays", "Mixing Consoles", "Wireless Mics", "Acoustics"]],
  ["live-streaming-production", "Live Streaming Production", "Hybrid Events", "Full-service live streaming with multi-camera switching, platform integration, virtual backdrops and real-time graphics.", "/mms/DSC_9244.jpg", ["/mms/DSC_9244.jpg", "/mms/DSC_7215.jpg"], ["Multi-camera Streaming", "Platform Integration", "Virtual Backdrops", "Live Graphics", "Replay & Editing"]],
  ["videography-photography", "Videography & Photography", "Creative Capture", "Cinematic event videography and professional photography, from same-day edits to complete event archives and brand campaigns.", "/mms/DSC_2327-Edit.jpg", ["/mms/DSC_2327-Edit.jpg", "/mms/DSC_2484.jpg", "/mms/DSC_2591.jpg"], ["Event Videography", "Photography", "Highlight Reels", "Same-day Edit", "Post-production"]],
  ["event-lighting-stage-setup", "Event Lighting & Stage Setup", "Stage Design", "Complete stage design, theatrical lighting, truss rigging and branded backdrops that transform any venue.", "/mms/DSC_7356.jpg", ["/mms/DSC_7356.jpg", "/mms/DSC_7317.jpg", "/mms/DSC_7343.jpg"], ["Stage Design", "Lighting Design", "Truss & Rigging", "LED Walls", "Backdrops"]],
];

const projects = [
  ["global-summit-production", "Global Summit Production", "Conference", 2024, "/mms/DSC_9244.jpg", "A fully produced conference experience with multiple screens, live streaming and branded stages for an international delegation.", ["/mms/DSC_7176.jpg", "/mms/DSC_7215.jpg"], ["Event Production", "Live Streaming", "AV Staging"]],
  ["victoria-falls-wedding-film", "Victoria Falls Wedding Film", "Wedding", 2024, "/mms/DSC_1257.jpg", "An emotional, intimate cinematic film captured across waterfall light and golden celebration moments.", ["/mms/DSC_0453.jpg", "/mms/AllanLinda-31.jpg"], ["Cinematography", "Editing", "Colour Grading"]],
  ["corporate-brand-experience", "Corporate Brand Experience", "Brand", 2024, "/mms/DSC_2484.jpg", "Interactive screens, digital podiums and branded media for a multi-day corporate event.", ["/mms/DSC_2349.jpg", "/mms/DSC_2591.jpg"], ["Brand Strategy", "Motion Design", "Content Creation"]],
  ["institutional-conference", "Institutional Conference", "Conference", 2023, "/mms/DSC_7218.jpg", "End-to-end production for a ministerial conference with interpretation, photography and live documentation.", ["/mms/DSC_7188.jpg", "/mms/DSC_7262.jpg"], ["Corporate Events", "Digital Displays", "Live Capture"]],
  ["immersive-media-production", "Immersive Media Production", "Immersive", 2023, "/mms/IMG_9198.jpeg", "360° capture, drone sequences and podcast experiences transformed the event into shareable digital stories.", ["/mms/_MG_0072.jpg", "/mms/IMG_9220.jpeg"], ["Immersive Tech", "Drone Cinematography", "360° Capture"]],
  ["destination-wedding-in-victoria-falls", "Destination Wedding in Victoria Falls", "Wedding", 2023, "/mms/DSC_1821.jpg", "Cinematic multi-day wedding coverage with drone aerials, ceremony films and same-day edits.", ["/mms/DSC_0676.jpg", "/mms/DSC_1349.jpg"], ["Wedding Film", "Drone", "Same-Day Edit"]],
  ["luxury-brand-campaign", "Luxury Brand Campaign", "Brand", 2023, "/mms/DSC_2327-Edit.jpg", "A polished visual campaign combining product, lifestyle and motion content for a premium regional brand.", ["/mms/DSC_2260.jpg", "/mms/DSC_2297.jpg"], ["Advertising", "Motion", "Photography"]],
  ["360-event-experience", "360 Event Experience", "Immersive", 2022, "/mms/DSC_7356.jpg", "An immersive event story built with 360-degree film, aerial coverage and interactive media.", ["/mms/DSC_7317.jpg", "/mms/IMG_9203.jpeg"], ["360° Film", "Drone", "Interactive"]],
  ["regional-development-forum", "Regional Development Forum", "Conference", 2022, "/mms/DSC_7703.jpg", "Multi-camera production and a complete visual archive for a regional development forum.", ["/mms/DSC_7704.jpg", "/mms/DSC_7258.jpg"], ["Multi-Camera", "Documentation", "Archive"]],
  ["intimate-riverside-ceremony", "Intimate Riverside Ceremony", "Wedding", 2022, "/mms/DSC_1864.jpg", "Natural, intimate wedding coverage shaped by riverside light and quiet documentary moments.", ["/mms/untitled-455.jpg", "/mms/untitled-477.jpg"], ["Intimate Wedding", "Natural Light", "Film"]],
  ["african-distillers-campaign", "African Distillers Campaign", "Brand", 2022, "/mms/DSC_2643 (2).jpg", "Product and lifestyle photography designed for a contemporary African beverage campaign.", ["/mms/DSC_2660 (2).jpg", "/mms/DSC_2505.jpg"], ["Product Photography", "Brand", "Lifestyle"]],
  ["drone-aerial-series", "Drone Aerial Series", "Immersive", 2022, "/mms/DSC_7906.jpg", "A cinematic aerial series capturing destination landscapes and event environments from above.", ["/mms/_MG_0305.jpg", "/mms/_MG_2920.jpg"], ["Drone", "Aerial", "Landscape"]],
];

for (const [sortOrder, row] of services.entries()) { const [slug,title,category,description,heroImage,gallery,features]=row; await db.service.upsert({where:{slug},update:{title,category,description,heroImage,gallery,features,sortOrder},create:{slug,title,category,description,heroImage,gallery,features,sortOrder}}); }
for (const [sortOrder, row] of projects.entries()) { const [slug,title,category,year,heroImage,description,gallery,tags]=row; await db.project.upsert({where:{slug},update:{title,category,year,heroImage,description,gallery,tags,sortOrder},create:{slug,title,category,year,heroImage,description,gallery,tags,sortOrder}}); }
console.log(`Seeded ${services.length} services and ${projects.length} projects.`);
await db.$disconnect();
